# Generated by Django 4.2.13 on 2026-05-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="shipper_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="trip",
            name="tractor_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="trip",
            name="trailer_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cycle_hours_used",
            field=models.FloatField(
                default=0, help_text="Hours already used in current 70-hour cycle"
            ),
        ),
    ]
